# -*- coding: utf-8 -*-
"""lesson_3.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2jfz7fABSYvQPf0_SI-hxvBQp4nB8_U
"""

# Тоже самое я бы написал сам: https://github.com/savoirfairelinux/num2words/blob/master/num2words/lang_EN.py
# Готовые сопоставления = !pip install num2words
from num2words import num2words

def checkNumber(PotentialNumber: str) -> bool:
  try:
    checkResult = int(PotentialNumber)
    return True
  except Exception:
    return False

def replaceNumberToWord(UserLetter: str) -> str:
  Letters = UserLetter.split(' ')
  ResultUserLetters = []
  for letter in Letters:
    if checkNumber(letter):
      # Находим сопоставление числа со буквенным обозначением
      ResultUserLetters.append(num2words(letter))
    else:
      ResultUserLetters.append(letter)
  return ' '.join(ResultUserLetters)


testNumberToWord = [
    '12 rub', '102 rub',
    '12', '102 rub and 42 rub',
]


for testNumber in testNumberToWord:
  print(f"{testNumber} = {replaceNumberToWord(testNumber)}")