# -*- coding: utf-8 -*-
"""lesson_5.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2jfz7fABSYvQPf0_SI-hxvBQp4nB8_U
"""

import math

n = int(input("n = "))
userNumber = [int(input(f"x{number+1} = ")) for number in range(n)]

def createMatrix(n: int, userNumber: list) -> list:
  matrixFromSin = [[1] * n for _ in range(n)]
  for i in range(n):
    for j in range(n):
      if i == 1:
        matrixFromSin[i][j] = userNumber[j]
      if i == 2:
        matrixFromSin[i][j] = userNumber[j]**(n-1)
  return matrixFromSin


createMatrix(n, userNumber)