# -*- coding: utf-8 -*-
"""lesson_5.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2jfz7fABSYvQPf0_SI-hxvBQp4nB8_U
"""

import math

n = int(input("n = "))

def createMatrix(n: int) -> list:
  matrixFromSin = [[0] * n for _ in range(n)]
  for i in range(1, n+1):
    for j in range(1, n+1):
      matrixFromSin[i-1][j-1] = math.sin(
          ((i**2 - j**2) / n)
      )
  return matrixFromSin


def showMatrix(userMatrix: list) -> None:
  for row in range(len(userMatrix)):
     print(userMatrix[row])


def calculatePositiveNumber(userMatrix: list):
  matrixLenght = len(userMatrix)
  countPositiveNumber = 0
  for i in range(matrixLenght):
    for j in range(matrixLenght):
      if userMatrix[i][j] > 0:
        countPositiveNumber += 1
  return countPositiveNumber

showMatrix(
    createMatrix(n)
)

calculatePositiveNumber(
    createMatrix(n)
)

